/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jursery_app_touchlearn_TouchLearnUtils */

#ifndef _Included_com_jursery_app_touchlearn_TouchLearnUtils
#define _Included_com_jursery_app_touchlearn_TouchLearnUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jursery_app_touchlearn_TouchLearnUtils
 * Method:    nativeGetKernelVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jursery_app_touchlearn_TouchLearnUtils_nativeGetKernelVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
